/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2015-05-28 19:00:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tag.webjms;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Iterator;
import org.apache.activemq.broker.jmx.ConnectionViewMBean;

public final class forEachConnection_tag
    extends javax.servlet.jsp.tagext.SimpleTagSupport
    implements org.apache.jasper.runtime.JspSourceDependent {


  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.servlet.jsp.JspContext jspContext;
  private java.io.Writer _jspx_sout;
  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public void setJspContext(javax.servlet.jsp.JspContext ctx) {
    super.setJspContext(ctx);
    java.util.ArrayList _jspx_nested = null;
    java.util.ArrayList _jspx_at_begin = null;
    java.util.ArrayList _jspx_at_end = null;
    this.jspContext = new org.apache.jasper.runtime.JspContextWrapper(ctx, _jspx_nested, _jspx_at_begin, _jspx_at_end, null);
  }

  public javax.servlet.jsp.JspContext getJspContext() {
    return this.jspContext;
  }
  private java.lang.String connection;
  private java.lang.String connectionName;
  private org.apache.activemq.web.BrokerFacade broker;
  private java.lang.String connectorName;

  public java.lang.String getConnection() {
    return this.connection;
  }

  public void setConnection(java.lang.String connection) {
    this.connection = connection;
    jspContext.setAttribute("connection", connection);
  }

  public java.lang.String getConnectionName() {
    return this.connectionName;
  }

  public void setConnectionName(java.lang.String connectionName) {
    this.connectionName = connectionName;
    jspContext.setAttribute("connectionName", connectionName);
  }

  public org.apache.activemq.web.BrokerFacade getBroker() {
    return this.broker;
  }

  public void setBroker(org.apache.activemq.web.BrokerFacade broker) {
    this.broker = broker;
    jspContext.setAttribute("broker", broker);
  }

  public java.lang.String getConnectorName() {
    return this.connectorName;
  }

  public void setConnectorName(java.lang.String connectorName) {
    this.connectorName = connectorName;
    jspContext.setAttribute("connectorName", connectorName);
  }

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  private void _jspInit(javax.servlet.ServletConfig config) {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(config.getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(config);
  }

  public void _jspDestroy() {
  }

  public void doTag() throws javax.servlet.jsp.JspException, java.io.IOException {
    javax.servlet.jsp.PageContext _jspx_page_context = (javax.servlet.jsp.PageContext)jspContext;
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest) _jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse) _jspx_page_context.getResponse();
    javax.servlet.http.HttpSession session = _jspx_page_context.getSession();
    javax.servlet.ServletContext application = _jspx_page_context.getServletContext();
    javax.servlet.ServletConfig config = _jspx_page_context.getServletConfig();
    javax.servlet.jsp.JspWriter out = jspContext.getOut();
    _jspInit(config);
    jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,jspContext);
    if( getConnection() != null ) 
      _jspx_page_context.setAttribute("connection", getConnection());
    if( getConnectionName() != null ) 
      _jspx_page_context.setAttribute("connectionName", getConnectionName());
    if( getBroker() != null ) 
      _jspx_page_context.setAttribute("broker", getBroker());
    if( getConnectorName() != null ) 
      _jspx_page_context.setAttribute("connectorName", getConnectorName());

    try {
      out.write("\n\n\n\n\n\n\n");

	Iterator it = broker.getConnections(connectorName).iterator();
	while (it.hasNext()) {
		String conName = (String) it.next();
		ConnectionViewMBean con = broker.getConnection(conName);
		request.setAttribute(connectionName, conName);
		request.setAttribute(connection, con);

      out.write('\n');
      ((org.apache.jasper.runtime.JspContextWrapper) this.jspContext).syncBeforeInvoke();
      _jspx_sout = null;
      if (getJspBody() != null)
        getJspBody().invoke(_jspx_sout);
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,getJspContext());
      out.write('\n');

	}

      out.write("       \n    \n");
    } catch( java.lang.Throwable t ) {
      if( t instanceof javax.servlet.jsp.SkipPageException )
          throw (javax.servlet.jsp.SkipPageException) t;
      if( t instanceof java.io.IOException )
          throw (java.io.IOException) t;
      if( t instanceof java.lang.IllegalStateException )
          throw (java.lang.IllegalStateException) t;
      if( t instanceof javax.servlet.jsp.JspException )
          throw (javax.servlet.jsp.JspException) t;
      throw new javax.servlet.jsp.JspException(t);
    } finally {
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,super.getJspContext());
      ((org.apache.jasper.runtime.JspContextWrapper) jspContext).syncEndTagFile();
    }
  }
}
